CREATE OR REPLACE PROCEDURE BC_BH_NHANH_BTNGHIEPVU
    (B_MADVI VARCHAR2,B_NSD VARCHAR2,B_PAS VARCHAR2,
    B_MA_DVI VARCHAR2,B_PHONG VARCHAR2,B_MA_NV VARCHAR2,B_NGAYD NUMBER,
    B_NGAYC NUMBER,CS_KQ OUT PHT_TYPE.CS_TYPE,CS_KQ1 OUT PHT_TYPE.CS_TYPE)
AS
    B_LOI VARCHAR2(100);B_NGAYDN NUMBER;B_I1 NUMBER;B_NV VARCHAR2(10);
BEGIN
--B_LOI:=FHT_MA_NSD_KTRA(B_MADVI,B_NSD,B_PAS,'BH','','');
IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
IF FHT_MA_NSD_PHONG(B_MA_DVI,B_NSD)='TBH' THEN
    B_LOI:='loi:ban khong co quyen xem bao cao:loi';
    RAISE PROGRAM_ERROR;
END IF;
PBC_LAY_NV(B_MADVI,B_MA_DVI,B_NSD,B_PAS,B_PHONG);
--SELECT COUNT(*) INTO B_I1 FROM TEMP_BC_NV WHERE NV='BT';
--IF B_I1=0 THEN
--    B_LOI:='loi:Ban khong co quyen xem bao cao nay:loi'; RAISE PROGRAM_ERROR;
--END IF;
IF B_NGAYD IS NULL OR B_NGAYC IS NULL THEN
    B_LOI:='loi:Nhap ngay bao cao:loi'; RAISE PROGRAM_ERROR;
END IF;
B_NGAYDN:=ROUND(B_NGAYD,-4)+101;--B_LOI:='loi:Ma chua dang ky:loi';
DELETE TEMP_1;DELETE TEMP_2;DELETE TEMP_3;DELETE KET_QUA; COMMIT;

PBC_LAY_DVI(B_MADVI,B_MA_DVI,B_NSD,B_PAS,B_LOI);
IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
DELETE TEMP_BC_TS;
INSERT INTO TEMP_BC_TS VALUES (B_MA_DVI||'%',B_NGAYD,B_NGAYC);
PBC_LAY_NV(B_MADVI,B_MA_DVI,B_NSD,B_PAS,B_PHONG);
SELECT COUNT(*) INTO B_I1 FROM TEMP_BC_DVI;
IF B_I1=0 THEN
    INSERT INTO TEMP_2 (C1,C3,C4,C5,C7,N1,N2,N3,N4)  SELECT MA_DVI,
    LH_NV,FBC_MA_BH_TEN(MA_DVI,NV,SO_ID,NGAY_HT),PHONG,LH_NV,SO_ID,PHI,0,0
    FROM V_BC_BH_DTBH_MM WHERE (B_PHONG IS NULL OR PHONG=B_PHONG) AND LH_NV LIKE B_MA_NV||'%';
    
    BC_BH_THBT_MD(B_MADVI,B_MA_DVI,'',B_PHONG,'','','',B_NGAYD,B_NGAYC,B_LOI,'B');
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    INSERT INTO TEMP_2 (C1,C3,C4,C5,C7,N1,N2,N3,N4)
    SELECT C29,FBC_MA_BH(C29,C1,N13),FBC_MA_BH_TEN(C29,C1,N13,N11),C6,C18,N13,0,N7,0 FROM TEMP_1 WHERE C18  LIKE  B_MA_NV||'%';
    
    BC_BH_THBT_MD_CD(B_MADVI,B_MA_DVI,'',B_PHONG,'','','',B_NGAYD,B_NGAYC,B_LOI,'B');
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    INSERT INTO TEMP_2 (C1,C3,C4,C5,C7,N1,N2,N3,N4)
    SELECT C29,FBC_MA_BH(C29,C1,N13),FBC_MA_BH_TEN(C29,C1,N13,N11),C6,C18,N13,0,0,N7 FROM TEMP_1 WHERE C18  LIKE  B_MA_NV||'%';
ELSE
    
    INSERT INTO TEMP_2 (C1,C3,C4,C5,C7,N1,N2,N3,N4)  SELECT MA_DVI,
    LH_NV,FBC_MA_BH_TEN(MA_DVI,NV,SO_ID,NGAY_HT),PHONG,LH_NV,SO_ID,PHI,0,0
    FROM V_BC_BH_DTBH_MM,TEMP_BC_DVI WHERE MA_DVI=DVI
        AND (B_PHONG IS NULL OR PHONG=B_PHONG) AND LH_NV LIKE  B_MA_NV||'%';

    BC_BH_THBT_MD(B_MADVI,B_MA_DVI,'',B_PHONG,'','','',B_NGAYD,B_NGAYC,B_LOI,'B');
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    INSERT INTO TEMP_2 (C1,C3,C4,C5,C7,N1,N2,N3,N4)
    SELECT C29,FBC_MA_BH(C29,C1,N13),FBC_MA_BH_TEN(C29,C1,N13,N11),C6,C18,N13,0,N7,0
    FROM TEMP_1,TEMP_BC_DVI WHERE C29=DVI AND C18  LIKE  B_MA_NV||'%';
    
    BC_BH_THBT_MD_CD(B_MADVI,B_MA_DVI,'',B_PHONG,'','','',B_NGAYD,B_NGAYC,B_LOI,'B');
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    INSERT INTO TEMP_2 (C1,C3,C4,C5,C7,N1,N2,N3,N4)
    SELECT C29,FBC_MA_BH(C29,C1,N13),FBC_MA_BH_TEN(C29,C1,N13,N11),C6,C18,N13,0,0,N7 FROM TEMP_1,TEMP_BC_DVI
    WHERE C29=DVI AND C18  LIKE  B_MA_NV||'%';
END IF;
UPDATE TEMP_2 SET C4=(SELECT TEN FROM BH_MA_LHNV WHERE MA_DVI=TEMP_2.C1 AND MA=TEMP_2.C7);
INSERT INTO KET_QUA(C1,C3,C4,C5,N2,N3,N4,N10)
    SELECT C1,c7,C4,C5,SUM(NVL(N2,0)),SUM(NVL(N3,0)),SUM(NVL(N4,0)),N10
    FROM TEMP_2 GROUP BY C1,C7,C4,C5,N10;
UPDATE KET_QUA SET C6=(SELECT TEN FROM HT_MA_PHONG WHERE MA_DVI=KET_QUA.C1 AND MA=KET_QUA.C5);
UPDATE KET_QUA SET C2=(SELECT TEN FROM HT_MA_DVI WHERE MA=KET_QUA.C1);
commit;
OPEN CS_KQ FOR SELECT C1 MA_DVI,C2 TEN_DVI,C3 LH_NV, C4 TEN_NV,C5 PHONG,C6 TEN_PHONG,N2 DTPS,N3 BT_PB,N4 DP
    FROM KET_QUA ORDER BY C1,C5,N10;
OPEN CS_KQ1 FOR SELECT C3 LH_NV, C4 TEN_NV,SUM(N2) DTPS,SUM(N3) BT_PB,SUM(N4) DP
    FROM KET_QUA GROUP BY C3,C4,N10 ORDER BY N10;
EXCEPTION WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20105,B_LOI);
END;
/
CREATE OR REPLACE PROCEDURE BBH_BH_BC_BH_NHANH_BTTHCT
    (B_MADVI VARCHAR2,B_NSD VARCHAR2,B_PAS VARCHAR2,
    B_MA_DVI VARCHAR2,B_MA_NV VARCHAR2,B_PHONG VARCHAR2,B_LOAI_KH VARCHAR2,
    B_MA_KH VARCHAR2,B_BT VARCHAR2,B_NGAYD NUMBER,B_NGAYC NUMBER,CS_KQ OUT PHT_TYPE.CS_TYPE)
AS
    B_LOI VARCHAR2(100);B_NGAYDN NUMBER; B_N1 NUMBER; B_N2 NUMBER; B_I1 NUMBER;
BEGIN
B_LOI:=FHT_MA_NSD_KTRA(B_MADVI,B_NSD,B_PAS,'BH','','');
IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
IF FHT_MA_NSD_PHONG(B_MA_DVI,B_NSD)='TBH' THEN
    B_LOI:='loi:ban khong co quyen xem bao cao:loi';
    RAISE PROGRAM_ERROR;
END IF;
IF B_NGAYD IS NULL OR B_NGAYC IS NULL THEN
    B_LOI:='loi:Nhap ngay bao cao:loi'; RAISE PROGRAM_ERROR;
END IF;
B_NGAYDN:=ROUND(B_NGAYD,-4)+101;B_LOI:='loi:Ma chua dang ky:loi';
DELETE TEMP_1;DELETE TEMP_2;DELETE KET_QUA; COMMIT;
PBC_LAY_DVI(B_MADVI,B_MA_DVI,B_NSD,B_PAS,B_LOI);
IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
PBC_LAY_NV(B_MADVI,B_MA_DVI,B_NSD,B_PAS,B_PHONG);

SELECT COUNT(*) INTO B_I1 FROM TEMP_BC_NV WHERE NV='BT';
IF B_I1=0 THEN
    B_LOI:='loi:Ban khong co quyen xem bao cao nay:loi'; RAISE PROGRAM_ERROR;
END IF;
DELETE TEMP_BC_TS;
INSERT INTO TEMP_BC_TS VALUES (B_MA_DVI||'%',B_NGAYD,B_NGAYC);
SELECT COUNT(*) INTO B_I1 FROM TEMP_BC_DVI;
EXECUTE IMMEDIATE 'TRUNCATE TABLE temp_1';
EXECUTE IMMEDIATE 'TRUNCATE TABLE temp_2';
EXECUTE IMMEDIATE 'TRUNCATE TABLE ket_qua';
IF B_I1=0 THEN
    
    BC_BH_THBT_MD_CD(B_MADVI,B_MA_DVI,B_MA_NV,B_PHONG,B_LOAI_KH,B_MA_KH,'',B_NGAYD,B_NGAYC,B_LOI,B_BT);
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    DELETE TEMP_1 WHERE C1 NOT IN (SELECT NV FROM TEMP_BC_NV);
    INSERT INTO TEMP_2 (C30,C10,C1,C2,C3,C4,C5,C6,C7,C17,N1,N2,N3,N10,N12,N13)
        SELECT C1,C29,C18,C4,C5,C6,C16,C7,C2,C17,N7,N7,0,N10,N12,N13 FROM TEMP_1;
    
    
    BBH_BH_BC_BH_THBT_MD(B_MADVI,B_MA_DVI,B_MA_NV,B_PHONG,B_LOAI_KH,B_MA_KH,'',B_NGAYD,B_NGAYC,B_LOI,B_BT);
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    DELETE TEMP_1 WHERE C1 NOT IN (SELECT NV FROM TEMP_BC_NV);
    INSERT INTO TEMP_2 (C30,C10,C1,C2,C3,C4,C5,C6,C7,C17,N1,N2,N3,N10,N12,N13)
        SELECT C1,C29,C18,C4,C5,C6,C16,C7,C2,C17,N7,0,N7,N10,N12,N13 FROM TEMP_1;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_BC_BH_DTBH_MM';
    BC_BH_LAY_BC_BH_DTBH_MM(B_MA_DVI,B_NGAYD,B_NGAYC);
    INSERT INTO TEMP_2 (C30,C10,C1,C2,C3,C4,C5,C6,C7,C17,N13,N15)
        SELECT NV,MA_DVI,LH_NV,SO_HD,MA_KH,PHONG,'','','',MA_NT,SO_ID,PHI
        FROM TEMP_BC_BH_DTBH_MM WHERE (B_PHONG IS NULL OR PHONG=B_PHONG) AND (B_MA_KH IS NULL OR MA_KH=B_MA_KH)
        AND (B_MA_NV IS NULL OR LH_NV LIKE B_MA_NV||'%');
ELSE
   
    BC_BH_THBT_MD_CD(B_MADVI,B_MA_DVI,B_MA_NV,B_PHONG,B_LOAI_KH,B_MA_KH,'',B_NGAYD,B_NGAYC,B_LOI,B_BT);
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    DELETE TEMP_1 WHERE C1 NOT IN (SELECT NV FROM TEMP_BC_NV);
    INSERT INTO TEMP_2 (C30,C10,C1,C2,C3,C4,C5,C6,C7,C17,N1,N2,N3,N10,N12,N13)
        SELECT C1,C29,C18,C4,C5,C6,C16,C7,C2,C17,N7,N7,0,N10,N12,N13 FROM TEMP_1,TEMP_BC_DVI WHERE C29=DVI ;
    
    BBH_BH_BC_BH_THBT_MD(B_MADVI,B_MA_DVI,B_MA_NV,B_PHONG,B_LOAI_KH,B_MA_KH,'',B_NGAYD,B_NGAYC,B_LOI,B_BT);
    IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
    DELETE TEMP_1 WHERE C1 NOT IN (SELECT NV FROM TEMP_BC_NV);
    INSERT INTO TEMP_2 (C30,C10,C1,C2,C3,C4,C5,C6,C7,C17,N1,N2,N3,N10,N12,N13)
    SELECT C1,C29,C18,C4,C5,C6,C16,C7,C2,C17,N7,0,N7,N10,N12,N13  FROM TEMP_1,TEMP_BC_DVI WHERE C29=DVI;
    
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_BC_BH_DTBH_MM';
    BC_BH_LAY_BC_BH_DTBH_MM(B_MA_DVI,B_NGAYD,B_NGAYC);
    INSERT INTO TEMP_2 (C30,C10,C1,C2,C3,C4,C5,C6,C7,C17,N13,N15)
        SELECT NV,MA_DVI,LH_NV,SO_HD,MA_KH,PHONG,'','','',MA_NT,SO_ID,PHI
        FROM TEMP_BC_BH_DTBH_MM,TEMP_BC_DVI WHERE MA_DVI=DVI AND (B_PHONG IS NULL OR PHONG=B_PHONG)
        AND (B_MA_KH IS NULL OR MA_KH=B_MA_KH) AND (B_MA_NV IS NULL OR LH_NV LIKE B_MA_NV||'%');
END IF;

UPDATE TEMP_2 SET (C22,C23) =(SELECT GCN,BIEN_XE FROM BH_XE_DS A,BH_BT_HS_NV B
    WHERE A.MA_DVI=TEMP_2.C10 AND A.SO_ID=FBH_HD_SO_ID_BS(TEMP_2.C10,TEMP_2.N13,30000101) AND
    A.MA_DVI=B.MA_DVI AND A.SO_ID_DT=B.SO_ID_DT
    AND B.SO_ID=TEMP_2.N10 AND ROWNUM=1) WHERE C30='XE';

UPDATE TEMP_2 SET (N22) =(SELECT SUM(A.TIEN) FROM BH_XE_DK A,BH_BT_HS_NV B
    WHERE A.MA_DVI=TEMP_2.C10 AND A.SO_ID=FBH_HD_SO_ID_BS(TEMP_2.C10,TEMP_2.N13,30000101)AND
    A.MA_DVI=B.MA_DVI AND A.SO_ID_DT=B.SO_ID_DT AND A.LH_NV=B.LH_NV
    AND B.SO_ID=TEMP_2.N10) WHERE C30='XE';

UPDATE TEMP_2 SET N29=(SELECT NVL(MAX(NGAY_TT),30000101) FROM BH_HD_GOC_TTPT WHERE MA_DVI=TEMP_2.C10 AND SO_ID=TEMP_2.N13 AND PT<>'C');

UPDATE TEMP_2 SET N14=NVL(N1,0) WHERE N12 BETWEEN B_NGAYD AND B_NGAYC;
UPDATE TEMP_2 SET C21 =(SELECT TEN FROM HT_MA_DVI WHERE MA=TEMP_2.C10);

update temp_2 set (c25,c26)=(select kieu_kt,ma_kt from bh_hd_goc where ma_dvi=temp_2.c10 and so_id=temp_2.n13);
update temp_2 set c27=(select ten from bh_dl_ma_kh where ma_dvi=temp_2.c10 and ma=c26) where c25 in ('D','M');
update temp_2 set c27=(select ten from ht_ma_cb where ma_dvi=temp_2.c10 and ma=c26) where c25='T';

/*
UPDATE
       (SELECT TEMP_2.C25 TEMP_2_C25, TEMP_2.C26 TEMP_2_C26, BH_HD_GOC.KIEU_KT BH_HD_GOC_KIEU_KT, BH_HD_GOC.MA_KT BH_HD_GOC_MA_KT
              FROM TEMP_2, BH_HD_GOC
             WHERE TEMP_2.C10 = BH_HD_GOC.MA_DVI AND TEMP_2.N13 = BH_HD_GOC.SO_ID)
       SET TEMP_2_C25 = BH_HD_GOC_KIEU_KT, TEMP_2_C26 = BH_HD_GOC_MA_KT;
UPDATE
       (SELECT TEMP_2.C27 TEMP_2_C27, BH_DL_MA_KH.TEN BH_DL_MA_KH_TEN
              FROM TEMP_2, BH_DL_MA_KH
             WHERE TEMP_2.C10 = BH_DL_MA_KH.MA_DVI AND TEMP_2.C26 = BH_DL_MA_KH.MA AND TEMP_2.C25 IN ('D','M'))
       SET TEMP_2_C27 = BH_DL_MA_KH_TEN;
UPDATE
       (SELECT TEMP_2.C27 TEMP_2_C27, HT_MA_CB.TEN HT_MA_CB_TEN
              FROM TEMP_2, HT_MA_CB
             WHERE TEMP_2.C10 = HT_MA_CB.MA_DVI AND TEMP_2.C26 = HT_MA_CB.MA AND TEMP_2.C25='T')
       SET TEMP_2_C27 = HT_MA_CB_TEN;
*/

INSERT INTO KET_QUA( C20,C10,C21,C1,C2,C3,C4,C5,C6,C7,N1,N2,N3,C22,C23,C25,C26,C27,N22,N29,N14,N30,N15)
    SELECT 'C',C10,C21,C1,C2,C3,C4,C5,C6,C7,SUM(NVL(N1,0)),SUM(NVL(N2,0)),SUM(NVL(N3,0)),
    C22,C23,C25,C26,C27,SUM(NVL(N22,0)),N29,SUM(NVL(N14,0)),
    (CASE SUBSTR(C1,1,2) WHEN U'XG' THEN 1 ELSE (CASE SUBSTR(C1,1,2) WHEN U'CN' THEN 2 ELSE
    (CASE SUBSTR(C1,1,2) WHEN U'HH' THEN 3 ELSE (CASE SUBSTR(C1,1,2) WHEN U'TT' THEN 4 ELSE
    (CASE SUBSTR(C1,1,2) WHEN U'TS' THEN 5 ELSE (CASE SUBSTR(C1,1,2) WHEN U'HP' THEN 6 ELSE
    (CASE SUBSTR(C1,1,2) WHEN U'TN' THEN 7 ELSE 0 END)  END) END) END) END) END) END),SUM(NVL(N15,0))
    FROM TEMP_2 GROUP BY C10,C21,C1,C2,C3,C4,C5,C6,C7,C22,C23,N29,C25,C26,C27;
DELETE KET_QUA WHERE NVL(N1,0)=0 AND NVL(N2,0)=0 AND NVL(N3,0)=0 AND NVL(N15,0)=0;

--update ket_qua set (c13,c5)=(select ten,loai from bh_hd_ma_kh where ma_dvi=ket_qua.c10 and ma=ket_qua.c3);
update
    (select ket_qua.c13 ket_qua_c13, ket_qua.c5 ket_qua_c5, bh_hd_ma_kh.ten bh_hd_ma_kh_ten, bh_hd_ma_kh.loai bh_hd_ma_kh_loai
        from ket_qua, bh_hd_ma_kh
        where ket_qua.c10 = bh_hd_ma_kh.ma_dvi and ket_qua.c3 = bh_hd_ma_kh.ma)
        set ket_qua_c13 = bh_hd_ma_kh_ten, ket_qua_c5 = bh_hd_ma_kh_loai;

update ket_qua set c14=(select ten from ht_ma_phong where ma_dvi=ket_qua.c10 and ma=ket_qua.c4);
update ket_qua set c15=(select ten from kh_ma_loai_dn where ma_dvi=ket_qua.c10 and ma=ket_qua.c5);
update ket_qua set c11=(select ten from bh_ma_lhnv where ma_dvi=ket_qua.c10 and ma=ket_qua.c1);

/*
UPDATE
    (SELECT KET_QUA.C13 KET_QUA_C13, KET_QUA.C5 KET_QUA_C5, BH_HD_MA_KH.TEN BH_HD_MA_KH_TEN, BH_HD_MA_KH.LOAI BH_HD_MA_KH_LOAI
        FROM KET_QUA, BH_HD_MA_KH
            WHERE KET_QUA.C10 = BH_HD_MA_KH.MA_DVI AND KET_QUA.C3 = BH_HD_MA_KH.MA)
        SET KET_QUA_C13 = BH_HD_MA_KH_TEN, KET_QUA_C5 = BH_HD_MA_KH_LOAI;
UPDATE
       (SELECT KET_QUA.C14 KET_QUA_C14, HT_MA_PHONG.TEN HT_MA_PHONG_TEN
              FROM KET_QUA, HT_MA_PHONG
             WHERE KET_QUA.C10 = HT_MA_PHONG.MA_DVI AND KET_QUA.C4 = HT_MA_PHONG.MA)
       SET KET_QUA_C14 = HT_MA_PHONG_TEN;
UPDATE
       (SELECT KET_QUA.C15 KET_QUA_C15, KH_MA_LOAI_DN.TEN KH_MA_LOAI_DN_TEN
              FROM KET_QUA, KH_MA_LOAI_DN
             WHERE KET_QUA.C10 = KH_MA_LOAI_DN.MA_DVI AND KET_QUA.C5 = KH_MA_LOAI_DN.MA)
       SET KET_QUA_C15 = KH_MA_LOAI_DN_TEN;
UPDATE
    (SELECT KET_QUA.C11 KET_QUA_C11, BH_MA_LHNV.TEN BH_MA_LHNV_TEN
        FROM KET_QUA, BH_MA_LHNV
             WHERE KET_QUA.C10 = BH_MA_LHNV.MA_DVI AND KET_QUA.C1 = BH_MA_LHNV.MA)
        SET KET_QUA_C11 = BH_MA_LHNV_TEN;
*/

COMMIT;
OPEN CS_KQ FOR SELECT C20 TC,C10 MA_DVI,C21 TEN_MA_DVI,C1 MA_NV,C11 TEN_NV,C3 MA_KH,
    C13 TEN_KH,C4 PHONG,C14 TEN_PHONG,C5 LOAI_KH,C15 TEN_LOAI,C2 SO_HD,'' SO_GCN,C6 NGAY_XR,C7 SO_HS,
    NVL(N1,0) TIEN_U,NVL(N3,0) TIEN_D,NVL(N2,0) TIEN_DGQ,NVL(N22,0) TIEN_BH,C22 GCN,C23 BIEN_XE,
    PKH_SO_CNG(N29) NGAY_TT,NVL(N14,0) TIEN_UTK,C26 MA_DL,C27 TEN_DL, NVL(N15,0) DTBH  FROM KET_QUA ORDER BY N30,C1;
EXCEPTION WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20105,B_LOI);
END;
/