CREATE OR REPLACE PROCEDURE BC_BH_BT_TSGQ
    (B_MADVI VARCHAR2,B_NSD VARCHAR2,B_PAS VARCHAR2,
    B_MA_DVI VARCHAR2,B_MA_NV VARCHAR2,B_PHONG VARCHAR2,B_LOAI_KH VARCHAR2,
    B_MA_KH VARCHAR2,B_TC VARCHAR2,B_TTRANG VARCHAR2,
    B_NGAYD NUMBER,B_NGAYC NUMBER,B_NV VARCHAR2,CS_KQ OUT PHT_TYPE.CS_TYPE)
AS
    B_LOI VARCHAR2(100);B_I1 NUMBER;B_TTRANG1 VARCHAR2(10);
BEGIN
B_LOI:=FHT_MA_NSD_KTRA(B_MADVI,B_NSD,B_PAS,'BH','','');
IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
IF B_NGAYD IS NULL OR B_NGAYC IS NULL THEN
    B_LOI:='loi:Nhap ngay bao cao:loi'; RAISE PROGRAM_ERROR;
END IF;
B_LOI:='loi:Ma chua dang ky:loi';
DELETE TEMP_1;DELETE TEMP_2;DELETE TEMP_BC_TS;DELETE KET_QUA; COMMIT;
INSERT INTO TEMP_BC_TS VALUES (B_MA_DVI||'%',B_NGAYD,B_NGAYC);
PBC_LAY_DVI(B_MADVI,B_MA_DVI,B_NSD,B_PAS,B_LOI);
IF B_LOI IS NOT NULL THEN RAISE PROGRAM_ERROR; END IF;
PBC_LAY_NV(B_MADVI,B_MA_DVI,B_NSD,B_PAS,B_PHONG);
SELECT COUNT(*) INTO B_I1 FROM TEMP_BC_NV WHERE NV='BT';
IF B_I1=0 THEN
    B_LOI:='loi:Ban khong co quyen xem bao cao nay:loi'; RAISE PROGRAM_ERROR;
END IF;

IF B_TTRANG<>'*' THEN B_TTRANG1:=B_TTRANG; END IF;
-- LAM SACH
-- INSERT INTO TEMP_1(C1,C29,C6,C18,C4,C5,C2,C7,C17,C19,N12,N7,N13,N10,C11,N8,C16,C12,C20,N21,C33)
--     SELECT NV,MA_DVI,PHONG,LH_NV,SO_HD,MA_KH,SO_HS,NGAY_XR,MA_NT,NGAY_GUI,NGAY_QD_N,TIEN_QD,SO_ID_HD,SO_ID,NGAY_QD_S,SO_ID_DT,
--                 NGAY_HL,NGAY_KT,TC,TIEN,MA_NT
--     FROM V_BC_BH_TH_BT WHERE (B_TTRANG1 IS NULL OR TTRANG=B_TTRANG1) AND (B_NV IS NULL OR NV=B_NV);
UPDATE TEMP_1 SET N7=ROUND(N7*(100- NVL((SELECT PT FROM BH_HD_DO_TL WHERE MA_DVI=C29 AND SO_ID=N13 AND PTHUC='D' AND ROWNUM=1),0))/100) WHERE C20='T';
UPDATE TEMP_1 SET N7=ROUND(N7*NVL((SELECT PT/100 FROM BH_HD_DO_TL WHERE NHA_BH=C29 AND SO_ID=N13  AND PTHUC='D' AND ROWNUM=1),1)) WHERE C20='K';
DELETE TEMP_1 WHERE N7=0;

DELETE TEMP_1 WHERE C1 NOT IN (SELECT NV FROM TEMP_BC_NV);
SELECT COUNT(*) INTO B_I1 FROM TEMP_BC_DVI;
IF B_I1=0 THEN
    INSERT INTO TEMP_2(C30,C29,C6,C1,C4,C5,C2,C7,C17,C19,N12,N6,N13,N10,C24,N18,C11,C12,C20,N21,C33)
        SELECT C1,C29,C6,C18,C4,C5,C2,C7,C17,C19,N12,N7,N13,N10,C11,N8,C16,C12,C20,N21,C33 FROM TEMP_1;
ELSE
    INSERT INTO TEMP_2(C30,C29,C6,C1,C4,C5,C2,C7,C17,C19,N12,N6,N13,N10,C24,N18,C11,C12,C20,N21,C33)
       SELECT C1,C29,C6,C18,C4,C5,C2,C7,C17,C19,N12,N7,N13,N10,C11,N8,C16,C12,C20,N21,C33 FROM TEMP_1,TEMP_BC_DVI
        WHERE C29=DVI;
END IF;


--SELECT COUNT(*) INTO B_I1 FROM TEMP_2;
--IF B_I1>65000 THEN
--    B_LOI:='loi:So dong bao cao > 65000. Lien he voi Tin hoc de tro giup:loi'; RAISE PROGRAM_ERROR;
--END IF;

BC_BH_THGD_MD(B_MADVI,B_MA_DVI,B_MA_NV,B_PHONG,B_LOAI_KH,B_MA_KH,B_NGAYD,B_NGAYC,B_LOI,'B');
--UPDATE TEMP_2 SET (N7,N22,C34)=(SELECT SUM(N7),SUM(N6),C17 FROM TEMP_1 WHERE C29=TEMP_2.C29 AND N30=TEMP_2.N10 AND C18=TEMP_2.C1 GROUP BY C17);
UPDATE TEMP_2 SET (N7,N22,C34)=(SELECT 0,tien,ma_nt FROM BH_BT_GD_HS WHERE MA_DVI=TEMP_2.C29 AND SO_ID_BT=TEMP_2.N10);

UPDATE TEMP_2 SET N8=(SELECT SUM(TIEN_QD) FROM BH_BT_NTBA_TT_PT WHERE MA_DVI=TEMP_2.C29 AND SO_ID_BT=TEMP_2.N10 AND LH_NV=TEMP_2.C1);

UPDATE TEMP_2 SET N9=(SELECT SUM(TIEN_QD) FROM BH_BT_THOI_PT WHERE MA_DVI=TEMP_2.C29 AND SO_ID_BT=TEMP_2.N10 AND LH_NV=TEMP_2.C1);

UPDATE TEMP_2 SET C28=(SELECT TEN FROM HT_MA_DVI WHERE MA=TEMP_2.C29);
UPDATE TEMP_2 SET C26=(SELECT TEN FROM HT_MA_PHONG WHERE MA_DVI=TEMP_2.C29 AND MA=TEMP_2.C6);
UPDATE TEMP_2 SET C21=(SELECT TEN FROM BH_MA_LHNV WHERE MA_DVI=TEMP_2.C29 AND MA=TEMP_2.C1);

--LAM SACH
-- UPDATE TEMP_2 SET N23=(SELECT case when KIEU = 'V' then  (sum(pt)/100) else (100 -  sum(pt))/100 end  FROM BH_HD_DO_TL WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 group by KIEU);
-- END LAM SACH

--UPDATE TEMP_2 SET (C25,C26)=(SELECT TEN,LOAI FROM BH_HD_MA_KH WHERE MA_DVI=TEMP_2.C29 AND MA=TEMP_2.C5);
update
    (select temp_2.c25 temp_2_c25, temp_2.c26 temp_2_c26, bh_hd_ma_kh.ten bh_hd_ma_kh_ten, bh_hd_ma_kh.loai bh_hd_ma_kh_loai
        from temp_2, bh_hd_ma_kh
        where temp_2.c29 = bh_hd_ma_kh.ma_dvi and temp_2.c5 = bh_hd_ma_kh.ma)
    set temp_2_c25 = bh_hd_ma_kh_ten, temp_2_c26 = bh_hd_ma_kh_loai;


UPDATE TEMP_2 SET N29=(SELECT NVL(MAX(NGAY_TT),30000101) FROM BH_HD_GOC_TTPT WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 AND PT<>'C');
IF B_NV='PHH' THEN
    UPDATE TEMP_2 SET C31=(SELECT MA_SP FROM BH_PHH WHERE MA_DVI=C29 AND SO_ID=N13);
    UPDATE TEMP_2 SET (C13,C14)=(SELECT DVI,DDIEM
        FROM BH_PHH_DVI WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET N19=(SELECT SUM(TIEN) FROM BH_PHH_DK
        WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET (N20)=(SELECT SUM(TIEN) FROM BH_PHh_DK
        WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET C21=(SELECT sp.TEN FROM bh_phh p,bh_phh_sp sp WHERE p.MA_DVI=TEMP_2.C29 AND p.SO_ID=TEMP_2.N13 and p.ma_sp = sp.ma);
    UPDATE TEMP_2 SET C16=(SELECT MA_NN FROM BH_BT_PHH WHERE MA_DVI=C29 AND SO_ID=TEMP_2.N10);
END IF;
IF B_NV='PKT' THEN
    UPDATE TEMP_2 SET C31=(SELECT MA_SP FROM BH_PKT WHERE MA_DVI=C29 AND SO_ID=N13);
    UPDATE TEMP_2 SET (C13,C14)=(SELECT kvuc,DDIEM
        FROM BH_PKT_Dvi WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET N19=(SELECT SUM(TIEN) FROM BH_PKT_DK
        WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET (N20)=(SELECT SUM(TIEN) FROM BH_PKT_DK
        WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET C21=(SELECT sp.TEN FROM bh_pkt p,bh_pkt_sp sp WHERE p.MA_DVI=TEMP_2.C29 AND p.SO_ID=TEMP_2.N13 and p.ma_sp = sp.ma);
    UPDATE TEMP_2 SET C16=(SELECT MA_NN FROM BH_BT_PKT WHERE MA_DVI=C29 AND SO_ID=TEMP_2.N10);
END IF;
IF B_NV='PTN' THEN
    UPDATE TEMP_2 SET C31=(SELECT NV FROM bh_ptn WHERE MA_DVI=C29 AND SO_ID=N13);
    UPDATE TEMP_2 SET (C13,C14)=(SELECT ten,dchi
        FROM bh_ptn WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13);-- AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET N19=(SELECT SUM(TIEN) FROM bh_ptn_DK
        WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13);-- AND SO_ID_DT=TEMP_2.N18);
    UPDATE TEMP_2 SET (N20)=(SELECT SUM(TIEN) FROM bh_ptn_DK
        WHERE MA_DVI=TEMP_2.C29 AND SO_ID=TEMP_2.N13 );--AND SO_ID_DT=TEMP_2.N18 );
END IF;
commit;
OPEN CS_KQ FOR SELECT C30 STT,C29 MA_DVI, C28 TEN_DVI, C6 MA_PHONG, C26 TEN_PHONG,C27 MA_LKH,
--    DECODE(C27,'1',unistr('Kh\00E1ch h\00E0ng trong ng\00E0nh'),unistr('Kh\00E1ch h\00E0ng ngo\00E0i ng\00E0nh')) TEN_LKH,
    TO_NUMBER(SUBSTR(C7,7,4)) NAM,
    C1 MA_NV, C21 TEN_NV, C25 TEN_KH, C4 SO_GCN,C31 RR_BH,
    DECODE(N29,30000101,unistr('Ch\01B0a n\1ED9p ph\00ED'),PKH_SO_CNG(N29)) NGAY_TT, C2 SO_HS,
    C7 NGAY_XR, C19 NGAY_GUI, PKH_SO_CNG(N12) NGAY_HS, NVL(N28,0) NGAY_TD,
    NVL(N6,0) TIEN_U,C22 GCN,C23 BIEN_XE,C24 NGAY_QD,NVL(N7,0) TIEN_G,NVL(N8,0)+NVL(N9,0) TIEN_THU,1 SO_VU,C5 MA_KH,
    C11 NGAY_HL,C12 NGAY_KT,C13 TEN_TS, C14 DIA_DIEM,NVL(N19,0) TIENBH, C16 TEN_NN, C16||'/'||C14 NN_DD_TT,C36 GHI_CHU,
    N20 TIEN_BH,C33 NT_TIEN,N21 TIEN_BT,C33 NT_BT,N22 TIEN_GD,C34 NT_GD,N23 PT_DO
    FROM TEMP_2 ORDER BY C29,C6,C1,C5;
EXCEPTION WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20105,B_LOI);
END;
